### ISSUE TITLE
Upstream this work?

### ISSUE THREAD

**Issue by dumblob** [juancarlospaco/dik#1]
I wonder whether this could at some point replace the upstream `Table`?

I know the signature is slightly different (namely the return type), but isn't it actually better?

**Comment by juancarlospaco** [comment]
You can try making an RFC here https://github.com/nim-lang/RFCs/issues

I am tired of my contributions getting rejected upstream anyway...

**Comment by juancarlospaco** [comment]
Closing because is not really a bug in the code.

**Comment by dumblob** [comment]
Yep, I totally understand (I feel this problem for over many years already).

Anyway, thanks for making this package, it's useful!
